#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mem=20G
#SBATCH --constraint=avx2
#SBATCH --job-name=mergeBigWigs

set -e

# Provide the directory with bigwig files generated by make_alignmentDepth_bigwig.sh
OUTDIR=$1
FINAL_OUTFILE=$2
CHROMSIZES=$3


echo "Merging..."

bigWigMerge $(ls $OUTDIR/ssa*.bw) $OUTDIR/all.bedGraph 

echo "Converting bedGraphToBigWig..."
bedGraphToBigWig $OUTDIR/all.bedGraph $CHROMSIZES $OUTDIR/all.bw
rm $OUTDIR/all.bedGraph

echo "Filling in the gaps..."
module load R/4.3.3
Rscript fixMergedBigWig.R -i $OUTDIR/all.bw -o $FINAL_OUTFILE

rm $OUTDIR/all.bw

echo "Done."
